"""empty message

Revision ID: bd59b32273e0
Revises: 
Create Date: 2023-09-20 13:38:43.771052

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'bd59b32273e0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contactus',
    sa.Column('contact_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('contact_email', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('contact_id')
    )
    op.drop_table('contact')
    with op.batch_alter_table('lga', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'state', ['state_id'], ['state_id'])

    with op.batch_alter_table('state', schema=None) as batch_op:
        batch_op.alter_column('state_name',
               existing_type=mysql.VARCHAR(length=80),
               type_=sa.String(length=30),
               existing_nullable=False,
               existing_server_default=sa.text("''"))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('state', schema=None) as batch_op:
        batch_op.alter_column('state_name',
               existing_type=sa.String(length=30),
               type_=mysql.VARCHAR(length=80),
               existing_nullable=False,
               existing_server_default=sa.text("''"))

    with op.batch_alter_table('lga', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    op.create_table('contact',
    sa.Column('contact_id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('contact_email', mysql.VARCHAR(length=100), nullable=True),
    sa.PrimaryKeyConstraint('contact_id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_table('contactus')
    # ### end Alembic commands ###
